VAR1=".n"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$1".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$2".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$3".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$4".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$5".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$6".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$7".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$8".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$9".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$10".nb"
cp /home/conor/Dropbox/01_post_grad_student_0/24_pgm_Daphne_Koller/10_topics/proteon_notebook.nb ./$11".nb"
xdg-open ./$1".nb"
